language: cpp
os:
  - linux
services:
  - docker
branches:
  only:
    - travis
before_install:
  - git submodule init && git submodule update
install:
  - docker build -t zeth-dev .
  - docker run -ti -p 50051:50051 --name zeth clearmatics/zeth-dev:latest

before_script:
  - docker run zeth /bin/sh -c "mkdir build && cd build && cmake .."

script:
  - docker run zeth /bin/sh -c "make && make check"

notifications:
email: false