language: cpp
os:
  - linux
services:
  - docker
branches:
  only:
    - travis
install:
  - docker pull clearmatics/zeth-dev:latest 
  - docker run -ti -p 50051:50051 --name zeth clearmatics/zeth-dev:latest

before_script:
  - git submodule init && git submodule update
  - mkdir build && cd build && cmake ..

script:
  - make
  - make check

notifications:
email: false